---
# key-pair.yml
- name: Create aws key pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"    
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: keypair

- name: Save private key
  copy: content="{{ keypair.key.private_key }}" dest="./aws.faasd.pem" mode=0600
  when: keypair.changed
      